-- Migration: Initialize BCP Schema
-- Created: 2026-01-08
-- Description: Complete Billing Control Plane (BCP) database schema
--              Includes Service Catalog, Offerings, Rate Cards, Account, and Job Processing

-- =============================================================================
-- EXTENSIONS
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =============================================================================
-- CUSTOM TYPES
-- =============================================================================

-- Docker ID domain for all BCP entity identifiers
-- Format: {prefix}_{body} where body is 28 chars of Crockford Base32 (31-34 chars total)
-- Generated by github.com/docker/id library
CREATE DOMAIN docker_id AS VARCHAR(34);

-- Feature types define the data type of a feature value
CREATE TYPE feature_type AS ENUM (
    'boolean',
    'integer',
    'string'
);

-- Metering types define how feature usage is tracked
CREATE TYPE metering_type AS ENUM (
    'static',
    'pre_calculated',
    'simple',
    'aggregated',
    'unit_conversion'
);

-- Offering package types define how offerings are packaged
CREATE TYPE offering_package_type AS ENUM (
    'bundle',
    'standalone',
    'add_on'
);

-- Monetization strategy types define how customers are charged (the 7 types from On-Rails)
CREATE TYPE monetization_strategy AS ENUM (
    'subscription',
    'payg',
    'prepaid'
    -- TODO: Expand to include all 7 On-Rails types: consumption, hybrid, commitment, etc.
);

-- Account types define who can purchase
CREATE TYPE account_type AS ENUM (
    'user',
    'organization'
);

-- Offering status
CREATE TYPE offering_status AS ENUM (
    'draft',
    'active',
    'archived'
);

-- Dependency types define relationships between strategies
CREATE TYPE dependency_type AS ENUM (
    'requires',
    'excludes',
    'recommended'
);

-- Transition types for lifecycle management
CREATE TYPE transition_type AS ENUM (
    'upgrade',
    'downgrade',
    'renewal',
    'migration'
);

-- Transition timing
CREATE TYPE transition_timing AS ENUM (
    'immediate',
    'end_of_period'
);

-- Pricing models define how pricing is calculated
CREATE TYPE pricing_model AS ENUM (
    'fixed',
    'per_unit',
    'block',
    'graduated',
    'volume',
    'fixed_plus_per_unit'
);

-- Feature aggregation defines how to combine features across entitlements
-- feature_aggregation: How to combine the same feature across multiple entitlements
-- IMPORTANT: These are offering declarations, NOT SQL aggregation functions
-- Application code implements the aggregation logic based on these values
-- Do NOT use SQL SUM(), MAX() - they won't respect business rules
CREATE TYPE feature_aggregation AS ENUM (
    'sum',     -- Add values together (e.g., seats: 100 + 50 = 150)
    'max',     -- Take highest value (e.g., storage: max(1TB, 500GB) = 1TB)
    'newest'   -- Use most recent value (e.g., support tier: newest subscription wins)
);

-- Billing timing
CREATE TYPE billing_timing AS ENUM (
    'advance',
    'arrears',
    'immediate'
);

-- Billing cycle
CREATE TYPE billing_cycle AS ENUM (
    'monthly',
    'annual',
    'multiyear',
    'one_time'
);

-- Recurrence period for entitlement refresh (separate from billing_cycle)
-- Includes 'daily' (e.g., daily API rate limits) which billing_cycle doesn't have
-- Excludes 'multiyear' which doesn't apply to entitlement refresh
CREATE TYPE recurrence_period AS ENUM (
    'daily',
    'monthly',
    'annual',
    'one_time'
);

-- Origin (sales channel)
CREATE TYPE origin AS ENUM (
    'self-serve',
    'inside-sales',
    'free-trial'
);

-- Source of entitlement/purchase
-- Expiration reasons
CREATE TYPE expiration_reason AS ENUM (
    'downgrade',
    'upgrade',
    'cancellation',
    'non_renewal'
);



-- Transition status for audit
CREATE TYPE transition_status AS ENUM (
    'scheduled',
    'executed',
    'cancelled'
);

-- Docker Money type (Google Proto Money compatible)
-- Represents monetary amounts with currency code and precise fractional values
CREATE TYPE docker_money AS (
    currency_code VARCHAR(3),    -- ISO 4217 currency code (e.g., 'USD', 'EUR')
    units BIGINT,                 -- Whole dollar amount (or other currency unit)
    nanos INTEGER                 -- Fractional amount in nano-units (0-999,999,999)
);

COMMENT ON TYPE docker_money IS 'Google Proto Money compatible type for precise monetary amounts. Uses currency_code + units + nanos to represent values like $0.00001400 as (USD, 0, 14000). Note: With Type+JSONB rate cards, monetary values are stored as google.type.Money JSON in pricing_details. This type is retained for reference and potential future use.';

-- =============================================================================
-- 1. SERVICE CATALOG
-- =============================================================================

CREATE TABLE services (
    id docker_id PRIMARY KEY,
    slug VARCHAR(63) NOT NULL UNIQUE,
    service_name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1
);

-- Note: No explicit index on slug needed — UNIQUE constraint creates one automatically.

COMMENT ON TABLE services IS 'Service catalog - defines groups of related features';
COMMENT ON COLUMN services.id IS 'Primary key with prefixed unique identifier';
COMMENT ON COLUMN services.slug IS 'Human-readable identifier (e.g., admin, hub, general, offload)';

-- Service features define individual capabilities within a service
-- IMPORTANT: feature_aggregation is defined here (not in rate_cards) to prevent conflicts
-- When a customer has multiple offerings with the same feature, we need ONE canonical
-- aggregation approach. By defining aggregation at the feature level, we ensure semantic
-- correctness: seats always sum, storage limits always use max, etc. This prevents impossible
-- configurations where different rate cards could declare conflicting aggregation for the same
-- feature.
-- Set feature_aggregation when creating rate cards that allow multiple purchases of this feature.
CREATE TABLE service_features (
    id docker_id PRIMARY KEY,
    service_id docker_id NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
    slug VARCHAR(63) NOT NULL,
    feature_name VARCHAR(255) NOT NULL,
    description TEXT,
    feature_type feature_type NOT NULL,
    mutable BOOLEAN NOT NULL DEFAULT false,
    metering_type metering_type,
    feature_aggregation feature_aggregation,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,

    UNIQUE(service_id, slug),
    UNIQUE(service_id, id)  -- Composite unique to enable composite FKs
);

CREATE INDEX idx_service_features_service ON service_features(service_id);
-- Note: No explicit index on (service_id, slug) needed — UNIQUE constraint creates one automatically.

COMMENT ON TABLE service_features IS 'Individual features within a service';
COMMENT ON COLUMN service_features.id IS 'Primary key with prefixed unique identifier';
COMMENT ON COLUMN service_features.mutable IS 'Can feature value change through purchase/ops (NOT customer self-service settings)';
COMMENT ON COLUMN service_features.metering_type IS 'How feature usage is tracked (nullable for non-metered features)';
COMMENT ON COLUMN service_features.feature_aggregation IS 'How to combine this feature across multiple purchases/entitlements (sum/max/newest). NULL = no aggregation needed or not yet configured. Set when creating rate cards that enable multiple purchases. Defined at feature level to prevent conflicts when customer has multiple offerings with same feature.';

-- =============================================================================
-- 2. OFFERINGS
-- =============================================================================

-- Offering groups organize related offerings (product lines)
CREATE TABLE offering_groups (
    id docker_id PRIMARY KEY,
    slug VARCHAR(63) NOT NULL UNIQUE,
    group_name VARCHAR(255) NOT NULL,
    description TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1
);

-- Note: No explicit index on slug needed — UNIQUE constraint creates one automatically.

COMMENT ON TABLE offering_groups IS 'Product lines that group related offerings (e.g., DSoP, DHI, Scout)';
COMMENT ON COLUMN offering_groups.id IS 'Primary key with prefixed unique identifier';

-- Offerings define what customers can purchase (instances, not types)
CREATE TABLE offerings (
    id docker_id PRIMARY KEY,
    slug VARCHAR(63) NOT NULL UNIQUE,
    group_id docker_id NOT NULL REFERENCES offering_groups(id) ON DELETE RESTRICT,
    offering_name VARCHAR(255) NOT NULL,
    description TEXT,
    offering_package offering_package_type NOT NULL,  -- How is this offering packaged?
    monetization_strategy monetization_strategy NOT NULL,  -- Which monetization strategy type?
    account_type account_type NOT NULL,
    requires_offering_id docker_id REFERENCES offerings(id) ON DELETE SET NULL,
    external_id TEXT,  -- External system ID
    external_system VARCHAR(50),       -- External system name
    status offering_status NOT NULL DEFAULT 'active',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1
);

-- Note: No explicit index on slug needed — UNIQUE constraint creates one automatically.
CREATE INDEX idx_offerings_group ON offerings(group_id);
CREATE INDEX idx_offerings_status ON offerings(status);
CREATE INDEX idx_offerings_external ON offerings(external_id, external_system);

COMMENT ON TABLE offerings IS 'Defines what customers can buy - specific offerings like dsop-team, dsop-pro (instances, not types)';
COMMENT ON COLUMN offerings.id IS 'Primary key with prefixed unique identifier';
COMMENT ON COLUMN offerings.offering_package IS 'How is this offering packaged? bundle, standalone, or add_on';
COMMENT ON COLUMN offerings.monetization_strategy IS 'Which monetization strategy TYPE? subscription, payg (pay-as-you-go), prepaid, etc.';
COMMENT ON COLUMN offerings.account_type IS 'user or organization';
COMMENT ON COLUMN offerings.external_id IS 'External system identifier';
COMMENT ON COLUMN offerings.external_system IS 'External system name';

-- Offering services: Join table linking offerings to services
-- This is the source of truth for "which services are included in an offering"
-- offering_features then provides detailed feature configuration for these included services
CREATE TABLE offering_services (
    offering_id docker_id NOT NULL REFERENCES offerings(id) ON DELETE RESTRICT,
    service_id docker_id NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (offering_id, service_id)
);

CREATE INDEX idx_offering_services_offering ON offering_services(offering_id);
CREATE INDEX idx_offering_services_service ON offering_services(service_id);

COMMENT ON TABLE offering_services IS 'Declares which services are included in each offering. Source of truth for service inclusion - offering_features can only configure services listed here.';

-- Offering features: Default values for features in each offering
CREATE TABLE offering_features (
    id docker_id PRIMARY KEY,
    offering_id docker_id NOT NULL,
    service_id docker_id NOT NULL,
    feature_id docker_id NOT NULL,
    value TEXT,  -- NULL = unlimited
    recurrence_period recurrence_period NOT NULL DEFAULT 'one_time',  -- How often entitlement refreshes (independent of billing)
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,

    UNIQUE(offering_id, service_id, feature_id),
    -- Composite FKs to enforce referential integrity
    FOREIGN KEY (offering_id, service_id) REFERENCES offering_services(offering_id, service_id) ON DELETE RESTRICT,
    FOREIGN KEY (service_id, feature_id) REFERENCES service_features(service_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_offering_features_offering ON offering_features(offering_id);
CREATE INDEX idx_offering_features_feature ON offering_features(feature_id);

COMMENT ON TABLE offering_features IS 'Default feature values for each offering (NULL = unlimited)';
COMMENT ON COLUMN offering_features.id IS 'Primary key with prefixed unique identifier';
COMMENT ON COLUMN offering_features.value IS 'NULL = unlimited/infinite, otherwise the default value';
COMMENT ON COLUMN offering_features.recurrence_period IS 'How often this entitlement refreshes (default one_time = granted once, does not reset). Independent of billing cycle - e.g., monthly entitlement refresh with annual billing.';

-- Offering constraints: Business rules for mutable features
CREATE TABLE offering_constraints (
    id docker_id PRIMARY KEY,
    offering_id docker_id NOT NULL,
    service_id docker_id NOT NULL,
    feature_id docker_id NOT NULL,
    origin origin NOT NULL,
    minimum_allowed INTEGER,
    maximum_allowed INTEGER,  -- NULL = no maximum
    constraint_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,

    UNIQUE(offering_id, service_id, feature_id, origin),
    -- Composite FKs to enforce referential integrity
    FOREIGN KEY (offering_id, service_id) REFERENCES offering_services(offering_id, service_id) ON DELETE RESTRICT,
    FOREIGN KEY (service_id, feature_id) REFERENCES service_features(service_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_offering_constraints_offering ON offering_constraints(offering_id);
CREATE INDEX idx_offering_constraints_feature ON offering_constraints(feature_id);

COMMENT ON TABLE offering_constraints IS 'Business rules for mutable features (e.g., min/max seats by origin)';
COMMENT ON COLUMN offering_constraints.id IS 'Primary key with prefixed unique identifier';
COMMENT ON COLUMN offering_constraints.origin IS 'Sales channel (self-serve, inside-sales, etc.)';
COMMENT ON COLUMN offering_constraints.maximum_allowed IS 'NULL = no maximum limit';

-- Offering group memberships: M:N relationship between offerings and groups
CREATE TABLE offering_group_memberships (
    offering_id docker_id NOT NULL REFERENCES offerings(id) ON DELETE RESTRICT,
    group_id docker_id NOT NULL REFERENCES offering_groups(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    PRIMARY KEY (offering_id, group_id)
);

CREATE INDEX idx_ogm_group ON offering_group_memberships(group_id);
CREATE INDEX idx_ogm_offering ON offering_group_memberships(offering_id);

COMMENT ON TABLE offering_group_memberships IS 'M:N - offerings can belong to multiple groups';

-- Offering dependencies: Defines eligibility rules
CREATE TABLE offering_dependencies (
    id docker_id PRIMARY KEY,
    dependent_offering_id docker_id NOT NULL REFERENCES offerings(id) ON DELETE RESTRICT,
    required_offering_id docker_id REFERENCES offerings(id) ON DELETE RESTRICT,
    required_group_id docker_id REFERENCES offering_groups(id) ON DELETE RESTRICT,
    dependency_type dependency_type NOT NULL,
    constraint_message TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,

    CHECK (
        (required_offering_id IS NOT NULL AND required_group_id IS NULL) OR
        (required_offering_id IS NULL AND required_group_id IS NOT NULL)
    ),
    UNIQUE(dependent_offering_id, required_offering_id, required_group_id, dependency_type)
);

CREATE INDEX idx_offering_dependencies_dependent ON offering_dependencies(dependent_offering_id);
CREATE INDEX idx_offering_dependencies_required_offering ON offering_dependencies(required_offering_id);
CREATE INDEX idx_offering_dependencies_required_group ON offering_dependencies(required_group_id);

COMMENT ON TABLE offering_dependencies IS 'Eligibility rules (requires/excludes/recommended)';
COMMENT ON COLUMN offering_dependencies.id IS 'Primary key with prefixed unique identifier';
COMMENT ON COLUMN offering_dependencies.required_offering_id IS 'Specific offering required';
COMMENT ON COLUMN offering_dependencies.required_group_id IS 'Any offering from this group required';

-- Offering lifecycle transitions: Allowed upgrades/downgrades
CREATE TABLE offering_lifecycle_transitions (
    id docker_id PRIMARY KEY,
    from_offering_id docker_id NOT NULL REFERENCES offerings(id) ON DELETE RESTRICT,
    to_offering_id docker_id NOT NULL REFERENCES offerings(id) ON DELETE RESTRICT,
    transition_type transition_type NOT NULL,
    timing transition_timing NOT NULL,
    allowed BOOLEAN NOT NULL DEFAULT true,
    expires_at TIMESTAMPTZ,
    effective_date TIMESTAMPTZ,
    constraints JSONB,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,

    UNIQUE(from_offering_id, to_offering_id)
);

CREATE INDEX idx_offering_transitions_from ON offering_lifecycle_transitions(from_offering_id);
CREATE INDEX idx_offering_transitions_to ON offering_lifecycle_transitions(to_offering_id);

COMMENT ON TABLE offering_lifecycle_transitions IS 'Allowed transitions (upgrade/downgrade/renewal/migration)';
COMMENT ON COLUMN offering_lifecycle_transitions.id IS 'Primary key with prefixed unique identifier';

-- =============================================================================
-- 2.5 METERED RESOURCES (Must be before Rate Cards)
-- =============================================================================

-- Supported unit types (reference data)
CREATE TABLE supported_unit_types (
    unit_type VARCHAR(50) PRIMARY KEY,
    display_name VARCHAR(100) NOT NULL,
    description TEXT,
    category VARCHAR(50) NOT NULL,                     -- 'time', 'data', 'compute', 'requests'
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

COMMENT ON TABLE supported_unit_types IS 'Valid unit types for meters, defines standardized measurement units';

-- Meters define what can be measured (region-agnostic)
CREATE TABLE meters (
    id docker_id PRIMARY KEY,
    service_id docker_id NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
    feature_id docker_id NOT NULL REFERENCES service_features(id) ON DELETE RESTRICT,
    slug VARCHAR(63) NOT NULL,                            -- 'compute_seconds', 'build_minutes'
    meter_name VARCHAR(255) NOT NULL,
    unit_type VARCHAR(50) NOT NULL REFERENCES supported_unit_types(unit_type) ON DELETE RESTRICT,
    status VARCHAR(20) NOT NULL DEFAULT 'active',      -- 'active', 'provisioning', 'archived'
    external_meter_id TEXT,                              -- External meter ID
    external_status VARCHAR(50),                       -- 'provisioned', 'failed', 'pending' (NULL = not yet attempted)
    external_provisioned_at TIMESTAMPTZ,               -- When provisioned to external system
    archived_at TIMESTAMPTZ,
    archived_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,
    UNIQUE(service_id, slug),
    UNIQUE(id, service_id),  -- Composite unique to enable composite FKs
    FOREIGN KEY (service_id, feature_id) REFERENCES service_features(service_id, id) ON DELETE RESTRICT
);

CREATE INDEX idx_meters_service ON meters(service_id);
CREATE INDEX idx_meters_feature ON meters(feature_id);
CREATE INDEX idx_meters_status ON meters(status) WHERE status = 'active';

COMMENT ON TABLE meters IS 'Defines measurable usage dimensions for services';
COMMENT ON COLUMN meters.slug IS 'Unique identifier used in usage events (meter_slug field)';
COMMENT ON COLUMN meters.feature_id IS 'The feature this meter measures usage for';
COMMENT ON COLUMN meters.archived_at IS 'NULL = active (archival pattern - meters are never deleted)';

-- Metered resources: service-level registry of billable configurations
CREATE TABLE metered_resources (
    id docker_id PRIMARY KEY,
    service_id docker_id NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
    resource_slug VARCHAR(63) NOT NULL,                   -- '2cpu_8gb', 'standard_build', 'seat'
    resource_name VARCHAR(255) NOT NULL,                 -- '2 CPU, 8GB RAM', 'Seat'
    description TEXT,
    status VARCHAR(20) NOT NULL DEFAULT 'active',      -- 'active', 'archived'
    archived_at TIMESTAMPTZ,
    archived_reason TEXT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,
    UNIQUE(service_id, resource_slug),
    UNIQUE(service_id, id)  -- Composite unique to enable composite FKs
);

CREATE INDEX idx_metered_resources_service ON metered_resources(service_id);
CREATE INDEX idx_metered_resources_slug ON metered_resources(service_id, resource_slug);

COMMENT ON TABLE metered_resources IS 'Service-level registry of billable resource configurations - supports both usage-based (compute instances) and non-usage (seats, credits)';
COMMENT ON COLUMN metered_resources.resource_slug IS 'Unique identifier used in usage events (resource_slug field) or pricing references';
COMMENT ON COLUMN metered_resources.archived_at IS 'NULL = active (archival pattern - resources are never deleted)';

-- Join table: meters to resources (M:N relationship)
CREATE TABLE resource_meters (
    meter_id docker_id NOT NULL,
    resource_id docker_id NOT NULL,
    service_id docker_id NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (meter_id, resource_id),

    -- Composite FKs to enforce service_id consistency
    FOREIGN KEY (meter_id, service_id) REFERENCES meters(id, service_id) ON DELETE RESTRICT,
    FOREIGN KEY (resource_id, service_id) REFERENCES metered_resources(id, service_id) ON DELETE RESTRICT
);

CREATE INDEX idx_resource_meters_meter ON resource_meters(meter_id);
CREATE INDEX idx_resource_meters_resource ON resource_meters(resource_id);
CREATE INDEX idx_resource_meters_service ON resource_meters(service_id);

COMMENT ON TABLE resource_meters IS 'Links meters to resources (M:N) - one meter can track multiple resources, one resource can be measured by multiple meters. Enforces service_id consistency via composite FKs';

-- =============================================================================



-- =============================================================================
-- 3. RATE CARDS
-- =============================================================================

-- Rate cards use Type+JSONB pattern: a single consolidated table with a pricing_type
-- discriminator and a pricing_details JSONB column. This eliminates the need for 6
-- separate pricing child tables and avoids complex multi-table JOINs.
-- See 02-data-model.md for the JSONB structure per pricing type.

CREATE TABLE rate_cards (
    id docker_id PRIMARY KEY,
    offering_id docker_id NOT NULL REFERENCES offerings(id) ON DELETE RESTRICT,
    service_id docker_id NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
    feature_id docker_id NOT NULL,
    list_price BOOLEAN NOT NULL DEFAULT true,
    account_id docker_id,  -- NULL for list prices, specific account for custom pricing

    -- Type+JSONB: pricing_type discriminator + pricing_details blob
    pricing_type pricing_model NOT NULL,
    pricing_details JSONB NOT NULL,

    billing_timing billing_timing NOT NULL,
    billing_cycle billing_cycle NOT NULL,
    currency VARCHAR(3) NOT NULL DEFAULT 'USD',
    external_price_id TEXT,
    external_system VARCHAR(50),
    effective_date TIMESTAMPTZ NOT NULL,
    expiration_date TIMESTAMPTZ,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,

    UNIQUE(offering_id, service_id, feature_id, effective_date, account_id),
    UNIQUE(id, service_id),  -- Composite unique to enable composite FK from account_purchases
    FOREIGN KEY (service_id, feature_id) REFERENCES service_features(service_id, id) ON DELETE RESTRICT,

    -- JSONB validation: ensure required keys exist per pricing type
    CONSTRAINT valid_per_unit CHECK (
        pricing_type != 'per_unit' OR (
            pricing_details ? 'resource_id' AND
            pricing_details ? 'unit_price'
        )
    ),
    CONSTRAINT valid_fixed CHECK (
        pricing_type != 'fixed' OR (
            pricing_details ? 'resource_id' AND
            pricing_details ? 'fixed_price'
        )
    ),
    CONSTRAINT valid_fixed_plus_per_unit CHECK (
        pricing_type != 'fixed_plus_per_unit' OR (
            pricing_details ? 'resource_id' AND
            pricing_details ? 'base_price' AND
            pricing_details ? 'unit_price'
        )
    ),
    CONSTRAINT valid_graduated CHECK (
        pricing_type != 'graduated' OR (
            pricing_details ? 'resource_id' AND
            pricing_details ? 'tiers'
        )
    ),
    CONSTRAINT valid_volume CHECK (
        pricing_type != 'volume' OR (
            pricing_details ? 'resource_id' AND
            pricing_details ? 'tiers'
        )
    ),
    CONSTRAINT valid_block CHECK (
        pricing_type != 'block' OR (
            pricing_details ? 'resource_id' AND
            pricing_details ? 'blocks'
        )
    )
);

CREATE INDEX idx_rate_cards_offering ON rate_cards(offering_id);
CREATE INDEX idx_rate_cards_feature ON rate_cards(feature_id);
CREATE INDEX idx_rate_cards_pricing_type ON rate_cards(pricing_type);
CREATE INDEX idx_rate_cards_external_price ON rate_cards(external_price_id, external_system);
CREATE INDEX idx_rate_cards_account ON rate_cards(account_id) WHERE account_id IS NOT NULL;

COMMENT ON TABLE rate_cards IS 'Pricing definitions using Type+JSONB pattern. pricing_type discriminates the JSONB structure in pricing_details.';
COMMENT ON COLUMN rate_cards.id IS 'Primary key with prefixed unique identifier';
COMMENT ON COLUMN rate_cards.list_price IS 'true = list price, false = customer-specific';
COMMENT ON COLUMN rate_cards.account_id IS 'NULL for list prices, specific account for custom pricing';
COMMENT ON COLUMN rate_cards.pricing_type IS 'Discriminator: fixed, per_unit, graduated, volume, block, fixed_plus_per_unit';
COMMENT ON COLUMN rate_cards.pricing_details IS 'Proto-marshaled JSONB pricing configuration. Structure varies by pricing_type. Uses google.type.Money format for all monetary values (no decimals).';
COMMENT ON COLUMN rate_cards.external_price_id IS 'External system price ID';

-- =============================================================================
-- 4. ACCOUNT (Customer Entitlements & Purchases)
-- =============================================================================

-- Offering entitlements track which offering the account has (Team, Pro, Business)
CREATE TABLE offering_entitlements (
    id docker_id PRIMARY KEY,
    account_id docker_id NOT NULL,
    offering_id docker_id NOT NULL REFERENCES offerings(id) ON DELETE RESTRICT,
    origin origin NOT NULL,
    expired_at TIMESTAMPTZ,  -- NULL = active
    expiration_reason expiration_reason,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1
);

CREATE INDEX idx_offering_entitlements_account ON offering_entitlements(account_id);
CREATE INDEX idx_offering_entitlements_offering ON offering_entitlements(offering_id);
-- Covering index: unique partial index with INCLUDE for index-only scans on the hot path.
-- Avoids heap fetches when querying active entitlements for an account.
CREATE UNIQUE INDEX idx_offering_entitlements_unique_active
    ON offering_entitlements(account_id, offering_id)
    INCLUDE (id, origin, created_at, updated_at, version)
    WHERE expired_at IS NULL;

COMMENT ON TABLE offering_entitlements IS 'Offering-level membership - which offering the account has (Team, Pro, Business)';
COMMENT ON COLUMN offering_entitlements.id IS 'Primary key with prefixed unique identifier';
COMMENT ON COLUMN offering_entitlements.expired_at IS 'NULL = active, timestamp = expired (expiration pattern)';

-- Account purchases track individual feature purchases (seats, build minutes, storage, etc.)
CREATE TABLE account_purchases (
    id docker_id PRIMARY KEY,
    account_id docker_id NOT NULL,
    offering_id docker_id NOT NULL REFERENCES offerings(id) ON DELETE RESTRICT,
    rate_card_id docker_id NOT NULL,
    service_id docker_id NOT NULL REFERENCES services(id) ON DELETE RESTRICT,
    feature_id docker_id NOT NULL,
    value TEXT NOT NULL,  -- Purchased quantity or override
    purchase_date TIMESTAMPTZ NOT NULL,
    expires_at TIMESTAMPTZ,  -- When prepaid purchases expire (NULL for non-expiring)
    expired_at TIMESTAMPTZ,  -- NULL = active
    expiration_reason expiration_reason,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    version INTEGER NOT NULL DEFAULT 1,

    -- Composite FKs to enforce referential integrity
    FOREIGN KEY (service_id, feature_id) REFERENCES service_features(service_id, id) ON DELETE RESTRICT,
    FOREIGN KEY (rate_card_id, service_id) REFERENCES rate_cards(id, service_id) ON DELETE RESTRICT
);

CREATE INDEX idx_account_purchases_account ON account_purchases(account_id);
CREATE INDEX idx_account_purchases_rate_card ON account_purchases(account_id, rate_card_id);
-- Partial indexes for hot-path queries (only active rows)
CREATE INDEX idx_account_purchases_active_offering ON account_purchases(account_id, offering_id) WHERE expired_at IS NULL;
CREATE INDEX idx_account_purchases_active_feature ON account_purchases(account_id, service_id, feature_id) WHERE expired_at IS NULL;

COMMENT ON TABLE account_purchases IS 'Individual feature purchases - seats, build minutes, storage, etc. (free or paid)';
COMMENT ON COLUMN account_purchases.id IS 'Primary key with prefixed unique identifier';
COMMENT ON COLUMN account_purchases.value IS 'Purchased quantity or override value';
COMMENT ON COLUMN account_purchases.expires_at IS 'When prepaid purchases expire (NULL for non-expiring)';
COMMENT ON COLUMN account_purchases.expired_at IS 'NULL = active (expiration pattern)';

-- =============================================================================
-- TRIGGERS FOR updated_at
-- =============================================================================
-- =============================================================================
-- USAGE METERING INFRASTRUCTURE
-- =============================================================================


-- Function to automatically update updated_at timestamp
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ language 'plpgsql';

-- Apply triggers to all tables with updated_at
CREATE TRIGGER bump_services_updated_at BEFORE UPDATE ON services
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_service_features_updated_at BEFORE UPDATE ON service_features
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_offering_groups_updated_at BEFORE UPDATE ON offering_groups
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_offerings_updated_at BEFORE UPDATE ON offerings
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_offering_features_updated_at BEFORE UPDATE ON offering_features
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_offering_constraints_updated_at BEFORE UPDATE ON offering_constraints
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_offering_dependencies_updated_at BEFORE UPDATE ON offering_dependencies
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_offering_lifecycle_transitions_updated_at BEFORE UPDATE ON offering_lifecycle_transitions
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_rate_cards_updated_at BEFORE UPDATE ON rate_cards
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_offering_entitlements_updated_at BEFORE UPDATE ON offering_entitlements
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_account_purchases_updated_at BEFORE UPDATE ON account_purchases
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_meters_updated_at BEFORE UPDATE ON meters
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER bump_metered_resources_updated_at BEFORE UPDATE ON metered_resources
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
